management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'

server:
  port: 8088
spring:
  application:
    name: system-platform-hystrix
  cloud:
    consul:
      config:
        enabled: true
      host: loclahost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  boot:
    admin:
      client:
        url: "http://localhost:8083"
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"   #注意此格式非常严格，输入框中的hostname请与此对应
turbine:
  instanceUrlSuffix: /hystrix.stream    # 指定收集路径
  appConfig: system-platform-consumer     # 指定了需要收集监控信息的服务名，多个以“,”进行区分
  clusterNameExpression: "'default'"    # 指定集群名称,若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true    # 此配置默认为false，则服务是以host进行区分，若设置为true则以host+port进行区分
feign:
  hystrix:
    enabled: true