dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
    qos-enable: false
  cloud:
    subscribed-services: ${spring.application.name}
  protocol:
    id: dubbo
    name: dubbo
    port: 20883
  scan:
    base-packages: kuroneko.fun.system.platform.nacos.producer
server:
  port: 8086
spring:
  application:
    name: system-platform-nacos-producer-one
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: localhost:8848
        username: nacos
  boot:
    admin:
      client:
        url: "http://localhost:8083"
  security:
    user:
      name: admin
      password: admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
