management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
server:
  port: 8089
spring:
  application:
    name: system-platform-zuul
  cloud:
    consul:
      config:
        enabled: true
      host: loclahost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  zipkin:
    base-url: http://117.24.14.69:9411/
    sender:
      type: rabbit
    rabbitmq:
      addresses: 117.24.14.69:5672
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 117.24.14.69
    port: 5672
    username: guest
    password: guest

#    boot:
#        admin:
#            client:
#                url: "http://localhost:8083"
#feign:
#    hystrix:
#        enabled: true
zuul:
  routes:
    producer:
      path: /producer/**
      serviceId: system-platform-consul-producer
    consumer:
      path: /consumer/**
      serviceId: system-platform-conusl-consumer