server:
  port: 8082
spring:
  application:
    name: system-platform-backup
  security:
    user:
      name: admin
      password: admin
  zipkin:
    base-url: http://*.*.*.*:9411/
    sender:
      type: rabbit
    rabbitmq:
      addresses: *.*.*.*:5672
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    addresses: *.*.*.*
feign:
  hystrix:
    enabled: true
kuroneko:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: kuroneko
      docker: false
      dockerName: mysql8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
