management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
server:
  port: 8083
spring:
  application:
    name: system-platform-monitor
  cloud:
    consul:
      config:
        enabled: true
      host: loclahost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  boot:
    admin:
      discovery:
        ignored-services: consul
  security:
    user:
      name: admin
      password: admin
#      自定义同时钉钉自定义机器人 webhook
notify:
  dingtalk:
      webhook: https://oapi.dingtalk.com/robot/send?access_token=aa9050cab34edc994b1463d13b4a56cd97257eed469277aebe42f9a73184d55e
