#dubbo:
#  registry:
#    address: nacos://${spring.cloud.nacos.discovery.server-addr}
#  application:
#    id: ${spring.application.name}
#    name: ${spring.application.name}
#    qos-enable: false
#  cloud:
#    subscribed-services: ${spring.application.name}
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: 20881
#  scan:
#    base-packages: kuroneko.fun.system.platform.monitor
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8084
server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: localhost:8848
        username: nacos
  application:
    name: system-platform-monitor
