server:
  port: 8081
spring:
  application:
    name: system-platform-admin
  devtools:
    livereload:
      enabled: false
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      password: root
      url: jdbc:mysql://localhost:3306/kuroneko?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
      username: root


