management:
    endpoint:
        health:
            show-details: always
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: '*'

server:
    port: 8087
spring:
    application:
        name: system-platform-producer
    cloud:
        consul:
            config:
                enabled: true
            host: loclahost
            port: 8500
            discovery:
                service-name: ${spring.application.name}
    zipkin:
        base-url: http://*.*.*.*:9411/
        sender:
            type: rabbit
        rabbitmq:
            addresses: *.*.*.*:5672
    sleuth:
        sampler:
            probability: 1
    rabbitmq:
        port: 5672
        username: guest
        password: guest
        addresses: *.*.*.*

feign:
    hystrix:
        enabled: true
